import{randomBytes,scryptSync,timingSafeEqual,createHash}from'node:crypto';
export class HttpError extends Error{constructor(status,message){super(message);this.status=status}}
export const fail=(s,m)=>{throw new HttpError(s,m)};
export function hashPassword(p){if(typeof p!=='string'||p.length<12||p.length>256)throw Error('Password must be 12–256 characters.');const salt=randomBytes(16).toString('hex');return 'scrypt$'+salt+'$'+scryptSync(p,salt,64).toString('hex')}
export function verifyPassword(p,h){if(typeof p!=='string'||p.length>256||!/^scrypt\$[a-f0-9]{32}\$[a-f0-9]{128}$/.test(h||''))return false;const[,salt,key]=h.split('$');return timingSafeEqual(scryptSync(p,salt,64),Buffer.from(key,'hex'))}
export const token=()=>randomBytes(32).toString('hex');export const digest=v=>createHash('sha256').update(v||'').digest('hex');
export const equal=(a,b)=>{if(typeof a!=='string'||typeof b!=='string')return false;const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
export const text=(v,name,min=0,max=1000)=>{if(typeof v!=='string')fail(400,name+': text required.');const t=v.trim();if(t.length<min||t.length>max)fail(400,name+': invalid length.');return t};
export const email=v=>typeof v==='string'&&v.length<=254&&/^[^\s@<>\r\n]+@[^\s@<>\r\n]+\.[^\s@<>\r\n]+$/.test(v);
export function link(v,optional=true){if(v===''&&optional)return '';try{const u=new URL(v);if(u.protocol==='https:'&&!u.username&&!u.password&&v.length<=2048)return u.href}catch{}fail(400,'A valid https:// URL is required.')}
export function photo(v){if(typeof v!=='string')fail(400,'Invalid photo.');if(/^\/(uploads|assets)\/[A-Za-z0-9_.-]+\.(jpe?g|png|webp)$/.test(v))return v;const u=new URL(link(v,false));if(!['www.artevistas.eu','artevistas.eu'].includes(u.hostname)||!/\.(jpe?g|png|webp)$/i.test(u.pathname))fail(400,'Upload a photo or use an original Artevistas image.');return u.href}
export function validateProduct(v){const p={};p.id=text(v.id,'ID',2,100);if(!/^[a-z0-9][a-z0-9-]+$/.test(p.id))fail(400,'Invalid URL slug.');p.title=text(v.title,'Title',1,150);if(!['sculpture','painting','other'].includes(v.category))fail(400,'Invalid category.');p.category=v.category;if(!['on_request','available','reserved','sold'].includes(v.availability))fail(400,'Invalid availability.');p.availability=v.availability;p.price=v.price===null||v.price===''?null:Number(v.price);if(p.price!==null&&(!Number.isFinite(p.price)||p.price<0||p.price>100000000))fail(400,'Invalid price.');p.year=v.year===null||v.year===''?null:Number(v.year);if(p.year!==null&&(!Number.isInteger(p.year)||p.year<1900||p.year>2100))fail(400,'Invalid year.');for(const k of ['dimensions','sku'])p[k]=text(v[k]??'',k,0,150);for(const k of ['mediumEn','mediumRu'])p[k]=text(v[k]??'',k,0,300);for(const k of ['descriptionEn','descriptionRu'])p[k]=text(v[k]??'',k,0,6000);if(!Array.isArray(v.images)||!v.images.length||v.images.length>8)fail(400,'Provide 1–8 photos.');p.images=v.images.map(photo);if(!Array.isArray(v.tags)||v.tags.length>16)fail(400,'Provide up to 16 tags.');p.tags=[...new Set(v.tags.map(t=>text(t,'Tag',1,40)))];p.sourceUrl=v.sourceUrl?link(v.sourceUrl):'';p.published=v.published===true;p.featured=v.featured===true;return p}
export function validateInquiry(v,products){if(v.website)fail(400,'Request rejected.');const q={name:text(v.name,'Name',2,100),email:text(v.email,'Email',3,254),telegram:text(v.telegram??'','Telegram',0,33),city:text(v.city??'','City',0,160),message:text(v.message??'','Message',0,3000)};if(!email(q.email))fail(400,'Please provide a valid email.');if(q.telegram&&!/^@[a-zA-Z0-9_]{5,32}$/.test(q.telegram))fail(400,'Telegram must be @username (5–32 characters).');if(!['acquisition','commission','collaboration'].includes(v.kind))fail(400,'Invalid enquiry type.');q.kind=v.kind;if(v.consent!==true)fail(400,'Consent is required.');if(!Array.isArray(v.productIds)||v.productIds.length>20||v.productIds.some(id=>typeof id!=='string'))fail(400,'Invalid selection.');q.items=[...new Set(v.productIds)].map(id=>{const p=products.find(p=>p.id===id&&p.published);if(!p)fail(409,'A selected work is no longer published.');if(['sold','reserved'].includes(p.availability))fail(409,p.title+' is not available. Remove it from your selection.');return{id:p.id,title:p.title,price:p.price,sku:p.sku,availability:p.availability}});if(q.kind==='acquisition'&&!q.items.length)fail(400,'Select an artwork first.');q.submissionId=text(v.submissionId,'Submission key',8,100);if(!/^[a-zA-Z0-9_-]+$/.test(q.submissionId))fail(400,'Invalid submission key.');q.lang=v.lang==='ru'?'ru':'en';q.consent=true;q.consentVersion='2026-09-08';return q}
export function decodeImage(v){const m=typeof v==='string'&&v.match(/^data:image\/(jpeg|png|webp);base64,([A-Za-z0-9+/=]+)$/);if(!m||m[2].length>8*1024*1024)fail(400,'Use JPG, PNG or WebP, up to 6 MB.');const b=Buffer.from(m[2],'base64');if(b.length<16||b.length>6*1024*1024)fail(400,'Invalid image size.');const ok=m[1]==='jpeg'?b[0]===255&&b[1]===216&&b[2]===255:m[1]==='png'?b.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):b.toString('ascii',0,4)==='RIFF'&&b.toString('ascii',8,12)==='WEBP';if(!ok)fail(400,'File content does not match its image type.');return{buffer:b,ext:m[1]==='jpeg'?'jpg':m[1]}}
