import http from 'node:http';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import{randomUUID}from'node:crypto';import{HttpError,fail,text,email,link,photo,validateProduct,validateInquiry,decodeImage,hashPassword,verifyPassword,token,digest,equal}from'./security.mjs';import{channels,send}from'./notify.mjs';
const root=path.dirname(fileURLToPath(import.meta.url)),env=process.env,port=Number(env.PORT||3000),prod=env.NODE_ENV==='production';
const publicURL=new URL(env.PUBLIC_URL||'http://localhost:'+port),adminURL=new URL(env.ADMIN_URL||'http://adminpro.localhost:'+port);
if(prod&&(publicURL.protocol!=='https:'||adminURL.protocol!=='https:'||publicURL.origin===adminURL.origin))throw Error('Production requires separate HTTPS PUBLIC_URL and ADMIN_URL.');
const dataDir=path.resolve(root,env.DATA_DIR||'data'),uploads=path.join(dataDir,'uploads');fs.mkdirSync(uploads,{recursive:true,mode:0o700});
const db=new DatabaseSync(path.join(dataDir,'studio.sqlite'));db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');
db.exec(`CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY,v TEXT NOT NULL);CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,v TEXT NOT NULL,version INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS inquiries(id TEXT PRIMARY KEY,reference TEXT UNIQUE,submission_id TEXT UNIQUE,payload TEXT NOT NULL,status TEXT NOT NULL,created_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS deliveries(id TEXT PRIMARY KEY,inquiry_id TEXT NOT NULL REFERENCES inquiries(id) ON DELETE CASCADE,channel TEXT NOT NULL,state TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,next_at INTEGER NOT NULL,last_error TEXT);CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY,username TEXT NOT NULL,csrf TEXT NOT NULL,expires INTEGER NOT NULL);CREATE INDEX IF NOT EXISTS outbox_due ON deliveries(state,next_at);`);
fs.chmodSync(path.join(dataDir,'studio.sqlite'),0o600);
// A process restart invalidates old login sessions, including after CLI credential rotation.
db.prepare('DELETE FROM sessions').run();
if(!db.prepare("SELECT v FROM settings WHERE k='site'").get()){const seed=JSON.parse(fs.readFileSync(path.join(root,'seed.json'),'utf8'));db.exec('BEGIN');try{db.prepare("INSERT INTO settings VALUES('site',?)").run(JSON.stringify(seed.settings));for(const p of seed.products)db.prepare('INSERT INTO products VALUES(?,?,1)').run(p.id,JSON.stringify(p));db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}}
const authPath=path.join(dataDir,'admin.json');let auth=null;function reloadAuth(){try{auth=JSON.parse(fs.readFileSync(authPath,'utf8'))}catch{auth=null}}reloadAuth();
if(env.ADMIN_PASSWORD&&!auth){auth={username:env.ADMIN_USERNAME||'admin',hash:hashPassword(env.ADMIN_PASSWORD)};fs.writeFileSync(authPath,JSON.stringify(auth),{mode:0o600})}
function saveAuth(value){fs.writeFileSync(authPath+'.tmp',JSON.stringify(value),{mode:0o600});fs.renameSync(authPath+'.tmp',authPath);auth=value}
const products=()=>db.prepare('SELECT v,version FROM products ORDER BY rowid').all().map(r=>({...JSON.parse(r.v),version:r.version}));const settings=()=>JSON.parse(db.prepare("SELECT v FROM settings WHERE k='site'").get().v);
const retention=Math.max(1,Math.min(3650,Number(env.PRIVACY_RETENTION_DAYS)||180));
const enabled=env.INQUIRIES_ENABLED==='1'&&!!env.PRIVACY_CONTROLLER&&email(env.PRIVACY_CONTACT||'');
const flags=()=>({inquiriesEnabled:enabled,channels:channels(env),privacy:{controller:env.PRIVACY_CONTROLLER||'',contact:env.PRIVACY_CONTACT||'',retention},publicUrl:publicURL.origin});
const json=(res,status,obj)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(obj))};
const safeJson=v=>JSON.stringify(v).replace(/</g,'\\u003c');
function baseHeaders(res){res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://www.artevistas.eu https://artevistas.eu; connect-src 'self'; font-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'");if(prod)res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');}
const cookieName=prod?'__Host-MarkRoxStudio':'MarkRoxStudio';function setCookie(res,value,expire=false){res.setHeader('Set-Cookie',cookieName+'='+value+'; Path=/; HttpOnly; SameSite=Strict; '+(prod?'Secure; ':'')+'Max-Age='+(expire?'0':'28800'))}
function cookie(req){const v=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='));return v?v.slice(cookieName.length+1):''}
function getSession(req){const s=db.prepare('SELECT * FROM sessions WHERE hash=? AND expires>?').get(digest(cookie(req)),Date.now());return s||null}
function requireSession(req,mutation=false){const s=getSession(req);if(!s)fail(401,'Sign in to the studio.');if(mutation&&!equal(req.headers['x-csrf-token'],s.csrf))fail(403,'Invalid session token. Reload and sign in again.');return s}
const limits=new Map();function rate(req,namespace,max,ms){const ip=env.TRUST_PROXY==='1'?String(req.headers['x-forwarded-for']||req.socket.remoteAddress).split(',')[0].trim():req.socket.remoteAddress;const key=namespace+':'+ip,now=Date.now();let v=limits.get(key);if(!v||now>v.until){v={n:0,until:now+ms};limits.set(key,v)}v.n++;if(v.n>max)fail(429,'Too many requests. Please try again later.');if(limits.size>20000){for(const[k,x]of limits)if(x.until<now)limits.delete(k)}}
async function body(req){if(!String(req.headers['content-type']||'').startsWith('application/json'))fail(415,'JSON is required.');const max=9*1024*1024;if(Number(req.headers['content-length'])>max){req.resume();fail(413,'Request is too large.')}const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>max)fail(413,'Request is too large.');chunks.push(chunk)}try{const v=JSON.parse(Buffer.concat(chunks).toString('utf8'));if(!v||typeof v!=='object'||Array.isArray(v))fail(400,'JSON object required.');return v}catch(e){if(e instanceof HttpError)throw e;fail(400,'Invalid JSON.')}}
const transaction=fn=>{db.exec('BEGIN IMMEDIATE');try{const v=fn();db.exec('COMMIT');return v}catch(e){db.exec('ROLLBACK');throw e}};
function storedInquiry(row){return {...JSON.parse(row.payload),status:row.status,deliveries:db.prepare('SELECT channel,state,attempts,last_error FROM deliveries WHERE inquiry_id=?').all(row.id)}}
function adminState(){return {products:products(),settings:settings(),inquiries:db.prepare('SELECT * FROM inquiries ORDER BY created_at DESC LIMIT 1000').all().map(storedInquiry),flags:flags()}}
let processing=false;db.prepare("UPDATE deliveries SET state='pending' WHERE state='sending'").run();
async function processQueue(){if(processing)return;processing=true;try{const rows=db.prepare("SELECT * FROM deliveries WHERE state='pending' AND next_at<=? ORDER BY next_at LIMIT 10").all(Date.now());for(const d of rows){const row=db.prepare('SELECT * FROM inquiries WHERE id=?').get(d.inquiry_id);if(!row)continue;db.prepare("UPDATE deliveries SET state='sending',attempts=attempts+1 WHERE id=?").run(d.id);try{await send(d.channel,JSON.parse(row.payload),env);db.prepare("UPDATE deliveries SET state='sent',last_error=NULL WHERE id=?").run(d.id)}catch{const attempts=d.attempts+1;db.prepare('UPDATE deliveries SET state=?,next_at=?,last_error=? WHERE id=?').run(attempts>=5?'failed':'pending',Date.now()+Math.min(3600000,30000*2**attempts),'Delivery failed. Check connection credentials and provider status.',d.id)}}}finally{processing=false}}
function cleanup(){const now=Date.now();db.prepare('DELETE FROM sessions WHERE expires<?').run(now);db.prepare('DELETE FROM inquiries WHERE created_at<?').run(now-retention*86400000);for(const[k,v]of limits)if(v.until<now)limits.delete(k)}cleanup();
setInterval(()=>processQueue().catch(()=>{}),10000).unref();setInterval(cleanup,3600000).unref();
const staticTypes={'.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.webp':'image/webp'};
function serveFile(res,file){if(!fs.existsSync(file)||!fs.statSync(file).isFile())fail(404,'Not found.');res.writeHead(200,{'Content-Type':staticTypes[path.extname(file)]||'application/octet-stream','Cache-Control':file.includes('/uploads/')||file.includes('/assets/')?'public,max-age=86400':'no-cache'});fs.createReadStream(file).pipe(res)}
const escapeHtml=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const server=http.createServer(async(req,res)=>{baseHeaders(res);try{const host=String(req.headers.host||'').toLowerCase(),isAdmin=host===adminURL.host.toLowerCase(),isPublic=host===publicURL.host.toLowerCase();if(!isAdmin&&!isPublic&&!(!prod&&['127.0.0.1:'+port,'localhost:'+port].includes(host)))fail(421,'Unknown host.');const url=new URL(req.url,'http://'+host),pathname=url.pathname,mutation=['POST','PUT','PATCH','DELETE'].includes(req.method);if(mutation){const expected=(isAdmin?adminURL:publicURL).origin;if(req.headers.origin!==expected)fail(403,'Invalid request origin.');}
if(pathname.startsWith('/api/admin')&&!isAdmin&&prod)fail(404,'Not found.');
if(pathname==='/api/catalog'&&req.method==='GET')return json(res,200,{products:products().filter(p=>p.published),settings:settings(),flags:flags()});
if(pathname==='/api/admin/session'&&req.method==='GET'){const s=getSession(req);return json(res,200,s?{authenticated:true,username:s.username,csrf:s.csrf}:{authenticated:false})}
if(pathname==='/api/admin/login'&&req.method==='POST'){rate(req,'login',7,15*60000);reloadAuth();if(!auth)fail(503,'Studio account is not configured. Run npm run admin:setup on the server.');const v=await body(req);if(!equal(v.username,auth.username)||!verifyPassword(v.password,auth.hash))fail(401,'Incorrect username or password.');const raw=token(),csrf=token();db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(digest(raw),auth.username,csrf,Date.now()+28800000);setCookie(res,raw);return json(res,200,{authenticated:true,username:auth.username,csrf})}
if(pathname.startsWith('/api/admin/')){const s=requireSession(req,mutation);if(pathname==='/api/admin/logout'&&req.method==='POST'){db.prepare('DELETE FROM sessions WHERE hash=?').run(s.hash);setCookie(res,'',true);return json(res,200,{ok:true})}if(pathname==='/api/admin/state'&&req.method==='GET')return json(res,200,adminState());if(pathname==='/api/admin/account'&&req.method==='PUT'){rate(req,'account',6,15*60000);const v=await body(req);if(!verifyPassword(v.oldPassword,auth.hash))fail(403,'Current password is incorrect.');const username=text(v.username,'Username',3,80);if(!/^[A-Za-z0-9_.@-]+$/.test(username))fail(400,'Use letters, numbers, dots, underscores or hyphens.');if(v.newPassword!==v.confirmPassword)fail(400,'Passwords do not match.');let hash;try{hash=hashPassword(v.newPassword)}catch(e){fail(400,e.message)}saveAuth({username,hash});db.prepare('DELETE FROM sessions').run();setCookie(res,'',true);return json(res,200,{ok:true})}
if(pathname==='/api/admin/upload'&&req.method==='POST'){rate(req,'upload',80,3600000);const v=await body(req),image=decodeImage(v.image),name=randomUUID()+'.'+image.ext;fs.writeFileSync(path.join(uploads,name),image.buffer,{mode:0o600,flag:'wx'});return json(res,201,{url:'/uploads/'+name})}
if(pathname==='/api/admin/products'&&req.method==='POST'){const v=await body(req),p=validateProduct(v);if(db.prepare('SELECT id FROM products WHERE id=?').get(p.id))fail(409,'This URL slug already exists.');p.version=1;db.prepare('INSERT INTO products VALUES(?,?,1)').run(p.id,JSON.stringify(p));return json(res,201,p)}
if(pathname.startsWith('/api/admin/products/')){const id=decodeURIComponent(pathname.split('/')[4]),existing=db.prepare('SELECT * FROM products WHERE id=?').get(id);if(!existing)fail(404,'Artwork not found.');if(req.method==='DELETE'){db.prepare('DELETE FROM products WHERE id=?').run(id);return json(res,200,{ok:true})}if(req.method==='PUT'){const v=await body(req);if(v.id!==id)fail(400,'Cannot change an existing URL slug.');if(Number(v.version)!==existing.version)fail(409,'Another edit was saved. Reload the catalogue before editing again.');const p=validateProduct(v);p.version=existing.version+1;db.prepare('UPDATE products SET v=?,version=? WHERE id=?').run(JSON.stringify(p),p.version,id);return json(res,200,p)}}
if(pathname==='/api/admin/settings'&&req.method==='PUT'){const v=await body(req),out=settings();for(const k of ['name','headlineEn','headlineRu'])if(k in v)out[k]=text(v[k],k,1,150);for(const k of ['introEn','introRu'])if(k in v)out[k]=text(v[k],k,0,600);for(const k of ['bioEn','bioRu','moreEn','moreRu'])if(k in v)out[k]=text(v[k],k,0,8000);if('portrait'in v)out.portrait=photo(v.portrait);if('email'in v){if(v.email&&!email(v.email))fail(400,'Invalid public email.');out.email=v.email.trim()}for(const k of ['instagram','telegram'])if(k in v){out[k]=v[k]?link(v[k]):'';if(out[k]){const hosts=k==='instagram'?['instagram.com','www.instagram.com']:['t.me','telegram.me'];if(!hosts.includes(new URL(out[k]).hostname))fail(400,'Invalid '+k+' URL.')}}if('heroId'in v){if(!products().some(p=>p.id===v.heroId&&p.published))fail(400,'Select a published hero artwork.');out.heroId=v.heroId}db.prepare("UPDATE settings SET v=? WHERE k='site'").run(JSON.stringify(out));return json(res,200,out)}
if(pathname.startsWith('/api/admin/inquiries/')){const id=pathname.split('/')[4],q=db.prepare('SELECT id FROM inquiries WHERE id=?').get(id);if(!q)fail(404,'Enquiry not found.');if(req.method==='DELETE'){db.prepare('DELETE FROM inquiries WHERE id=?').run(id);return json(res,200,{ok:true})}if(req.method==='PATCH'){const v=await body(req);if(!['new','in_progress','closed'].includes(v.status))fail(400,'Invalid status.');db.prepare('UPDATE inquiries SET status=? WHERE id=?').run(v.status,id);return json(res,200,{ok:true})}if(req.method==='POST'&&pathname.endsWith('/retry')){db.prepare("UPDATE deliveries SET state='pending',attempts=0,next_at=?,last_error=NULL WHERE inquiry_id=? AND state='failed'").run(Date.now(),id);setImmediate(()=>processQueue().catch(()=>{}));return json(res,200,{ok:true})}}
fail(404,'Unknown studio endpoint.');}
if(pathname==='/api/inquiries'&&req.method==='POST'){if(!enabled)fail(503,'Enquiries are not enabled yet. The operator must configure contact and privacy settings.');rate(req,'enquiry',8,15*60000);const v=await body(req);if(typeof v.submissionId==='string'){const existing=db.prepare('SELECT payload FROM inquiries WHERE submission_id=?').get(v.submissionId);if(existing){const q=JSON.parse(existing.payload);return json(res,200,{id:q.id,reference:q.reference})}}const q=validateInquiry(v,products());q.id=randomUUID();q.reference='MR-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+q.id.slice(0,6).toUpperCase();q.createdAt=new Date().toISOString();transaction(()=>{db.prepare('INSERT INTO inquiries VALUES(?,?,?,?,?,?)').run(q.id,q.reference,q.submissionId,JSON.stringify(q),'new',Date.now());for(const c of channels(env))db.prepare('INSERT INTO deliveries VALUES(?,?,?,?,?,?,?)').run(randomUUID(),q.id,c,'pending',0,Date.now(),null)});setImmediate(()=>processQueue().catch(()=>{}));return json(res,201,{id:q.id,reference:q.reference})}
if(pathname.startsWith('/api/'))fail(404,'Unknown endpoint.');if(!['GET','HEAD'].includes(req.method))fail(405,'Method not allowed.');
if(pathname==='/runtime.js'){res.writeHead(200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'});return res.end('window.RUNTIME='+safeJson({demo:false,admin:isAdmin,dev:!prod,publicUrl:publicURL.origin})+';')}
if(pathname==='/seed.js'){res.writeHead(200,{'Content-Type':'text/javascript; charset=utf-8','Cache-Control':'no-store'});return res.end('window.SEED='+safeJson({products:products().filter(p=>p.published),settings:settings()})+';')}
if(pathname==='/robots.txt'){res.writeHead(200,{'Content-Type':'text/plain'});return res.end(isAdmin?'User-agent: *\nDisallow: /\n':'User-agent: *\nDisallow: /api/\nDisallow: /admin\nSitemap: '+publicURL.origin+'/sitemap.xml\n')}
if(pathname==='/sitemap.xml'&&!isAdmin){const urls=['/','/works','/artist','/contact',...products().filter(p=>p.published).map(p=>'/work/'+p.id)];res.writeHead(200,{'Content-Type':'application/xml'});return res.end('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(u=>'<url><loc>'+escapeHtml(publicURL.origin+u)+'</loc></url>').join('')+'</urlset>')}
if(pathname.startsWith('/uploads/')){const name=pathname.slice(9);if(!/^[A-Za-z0-9_.-]+\.(jpg|png|webp)$/.test(name))fail(404,'Not found.');return serveFile(res,path.join(uploads,name))}
if(pathname.startsWith('/assets/')){const name=decodeURIComponent(pathname.slice(8));if(!/^[A-Za-z0-9_.-]+\.(jpe?g|png|webp)$/.test(name))fail(404,'Not found.');return serveFile(res,path.join(root,'public','assets',name))}
if(['/style.css','/app.js','/assets.js','/favicon.svg'].includes(pathname))return serveFile(res,path.join(root,'public',pathname.slice(1)));
const known=['/','/works','/artist','/contact','/inquiry','/privacy','/success'];let title='MARK ROX — Art outside the orbit',status=200,desc='Mark Rox — paintings, ARTonaut sculptures and a different point of view.';
if(pathname==='/admin'){if(!isAdmin&&prod)status=404;title='Mark Rox / Private studio'}else if(pathname.startsWith('/work/')){const p=products().find(p=>p.id===pathname.slice(6)&&p.published);if(!p)status=404;else{title=p.title+' — Mark Rox';desc=p.descriptionEn.slice(0,220)}}else if(!known.includes(pathname))status=404;
let html=fs.readFileSync(path.join(root,'public/index.html'),'utf8');html=html.replace(/<title>.*?<\/title>/,'<title>'+escapeHtml(title)+'</title>').replace(/<meta name="description" content="[^"]*">/,'<meta name="description" content="'+escapeHtml(desc)+'">');html=html.replace('</head>',(isAdmin?'<meta name="robots" content="noindex,nofollow">':'<link rel="canonical" href="'+escapeHtml(publicURL.origin+pathname)+'">')+'</head>');res.writeHead(status,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache'});res.end(html);
}catch(err){if(!res.headersSent)json(res,err instanceof HttpError?err.status:500,{error:err instanceof HttpError?err.message:'A server error occurred. Please retry.'});else res.end();if(!(err instanceof HttpError))console.error('Request failed:',err.name)}});
server.requestTimeout=20000;server.headersTimeout=15000;server.keepAliveTimeout=5000;server.maxHeadersCount=60;
server.listen(port,env.HOST||'127.0.0.1',()=>{console.log('Mark Rox studio running on port '+port+'.');if(!auth)console.log('Set up a private account with npm run admin:setup.');console.log('Enquiries: '+(enabled?'enabled':'disabled until operator details are configured.'))});
function stop(){server.close(()=>{db.close();process.exit(0)});setTimeout(()=>process.exit(1),5000).unref()}process.on('SIGINT',stop);process.on('SIGTERM',stop);
